CinemaApp.Web/Controllers/GenreController.cs
using CinemaApp.DataAccess.Repository.IRepository;
using CinemaApp.Models.DomainModels;
using CinemaApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CinemaApp.Web.Controllers
{

	public class GenreController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

        public GenreController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Index()
		{	
			var genres = await _unitOfWork.Genre.GetAllAsync();
			return View(genres);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public IActionResult Create() 
		{
			return View();
		}

		public async Task<IActionResult> GenreMovies(int? genreId)
		{
			if (genreId == null || genreId == 0)
			{
				return NotFound();
			}

			var movieGenres = await _unitOfWork.MovieGenre.GetAllAsync(includeProperties: "Movie,Genre");
			var genre = movieGenres.Where(x => x.GenreId == genreId).Select(x => x.Genre).FirstOrDefault();
			var genreMovies = movieGenres.Where(x => x.GenreId == genreId).Select(x => x.Movie).ToList();

			TempData["GenreName"] = genre.Name;

			return View(genreMovies);
		}

		[Authorize(Roles = SD.Role_Employee)]
		[HttpPost]
		public async Task<IActionResult> Create(Genre genre)
		{
			if(ModelState.IsValid)
			{
				await _unitOfWork.Genre.AddAsync(genre);
				await _unitOfWork.SaveAsync();

				return RedirectToAction("Index");
			}
			return View();
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Edit(int? id)
		{	
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var genre = await _unitOfWork.Genre.GetAsync(id);

			if (genre == null)
			{
				return NotFound();
			}
			return View(genre);
		}

		[Authorize(Roles = SD.Role_Employee)]
		[HttpPost]
		public async Task<IActionResult> Edit(Genre genre)
		{
			if(ModelState.IsValid)
			{
				_unitOfWork.Genre.Update(genre);
				await _unitOfWork.SaveAsync();

				return RedirectToAction("Index");
			}
			return View(genre);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var genre = await _unitOfWork.Genre.GetAsync(id);

			if (genre == null)
			{
				return NotFound();
			}

			_unitOfWork.Genre.Remove(genre);
			await _unitOfWork.SaveAsync();

			return RedirectToAction("Index");
		}
	}
}

CinemaApp.Web/Controllers/MovieController.cs
using CinemaApp.DataAccess.Repository.IRepository;
using CinemaApp.Models.DomainModels;
using CinemaApp.Models.ViewModels;
using CinemaApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CinemaApp.Web.Controllers
{
	public class MovieController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _webHostEnvironment;

		public MovieController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
            _unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Index()
		{
			var movieGenres = await _unitOfWork.MovieGenre.GetAllAsync(includeProperties: "Movie,Genre");
			var movies = movieGenres.Select(x => x.Movie).Distinct().ToList();

			return View(movies);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Create()
		{
			var genres = await _unitOfWork.Genre.GetAllAsync();
			MovieVM movieVM = new MovieVM
			{
				Genres = genres,
				Movie = new Movie()
			};
			movieVM.Movie.ReleaseDate = DateTime.Now;
			return View(movieVM);
		}

		[Authorize(Roles = SD.Role_Employee)]
		[HttpPost]
		public async Task<IActionResult> Create(MovieVM movieVM, IFormFile? formFile)
		{
			if (ModelState.IsValid)
			{
				if (movieVM.SelectedGenreIds.Count <= 0)
				{
					ModelState.AddModelError("Movie.MovieGenres", "Movie must belongs to at least one genre.");
					movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
					return View(movieVM);
				}

				string wwwRootPath = _webHostEnvironment.WebRootPath;
				if (formFile != null)
				{
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
					string moviePath = Path.Combine(wwwRootPath, @"images\movie\");

					using (var fileStream = new FileStream(Path.Combine(moviePath, fileName), FileMode.Create))
					{
						formFile.CopyTo(fileStream);
					}
					movieVM.Movie.ImageUrl = @"\images\movie\" + fileName;
				} else
				{
					movieVM.Movie.ImageUrl = @"\images\default\default-movie-poster.jpg";
				}

				movieVM.Movie.MovieGenres = movieVM.SelectedGenreIds.Select(id => new MovieGenre { GenreId = id }).ToList();

				await _unitOfWork.Movie.AddAsync(movieVM.Movie);
				await _unitOfWork.SaveAsync();

				return RedirectToAction("Index");
			}
			movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
			return View(movieVM);
		}

		public async Task<IActionResult> Details(int? id)
		{
			var movieGenres = await _unitOfWork.MovieGenre.FindAsync(x => x.MovieId == id, includeProperties: "Movie,Genre");
			var movie = movieGenres.Select(x => x.Movie).FirstOrDefault();

			return View(movie);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var movieGenres = await _unitOfWork.MovieGenre.FindAsync(x => x.MovieId == id, includeProperties: "Movie,Genre");
			var movie = movieGenres.Select(x => x.Movie).FirstOrDefault();

			if (movie == null)
			{
				return NotFound();
			}

			MovieVM movieVM = new MovieVM
			{
				Movie = movie,
				SelectedGenreIds = movie.MovieGenres.Select(x => x.GenreId).ToList(),
				Genres = await _unitOfWork.Genre.GetAllAsync()
			};

			return View(movieVM);
		}

		[Authorize(Roles = SD.Role_Employee)]
		[HttpPost]
		public async Task<IActionResult> Edit(MovieVM movieVM, IFormFile? formFile)
		{
			if (ModelState.IsValid)
			{
				if (movieVM.SelectedGenreIds.Count <= 0)
				{
					ModelState.AddModelError("Movie.MovieGenres", "Movie must belongs to at least one genre.");
					movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
					return View(movieVM);
				}

				string wwwRootPath = _webHostEnvironment.WebRootPath;
				if (formFile != null)
				{
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
					string moviePath = Path.Combine(wwwRootPath, @"images\movie\");

					if (!string.IsNullOrEmpty(movieVM.Movie.ImageUrl))
					{
						var oldImagePath = Path.Combine(wwwRootPath, movieVM.Movie.ImageUrl.TrimStart('\\'));

						if (System.IO.File.Exists(oldImagePath) && !oldImagePath.Contains("default"))
						{
							System.IO.File.Delete(oldImagePath);
						}

					}
					using (var fileStream = new FileStream(Path.Combine(moviePath, fileName), FileMode.Create))
					{
						formFile.CopyTo(fileStream);
					}
					movieVM.Movie.ImageUrl = @"\images\movie\" + fileName;
				}

				movieVM.Movie.MovieGenres = (ICollection<MovieGenre>) await _unitOfWork.MovieGenre.FindAsync(x => x.MovieId == movieVM.Movie.Id);

				foreach (var genreId in movieVM.SelectedGenreIds)
				{
					if (!movieVM.Movie.MovieGenres.Any(x => x.GenreId == genreId))
					{
						movieVM.Movie.MovieGenres.Add(new MovieGenre { GenreId = genreId });
					}
				}

				foreach (var movieGenre in movieVM.Movie.MovieGenres)
				{
					if (!movieVM.SelectedGenreIds.Contains(movieGenre.GenreId))
					{
						_unitOfWork.MovieGenre.Remove(movieGenre);
					}
				}

				_unitOfWork.Movie.Update(movieVM.Movie);
				await _unitOfWork.SaveAsync();

				return RedirectToAction("Index");
			}
			movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
			return View(movieVM);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var movie = await _unitOfWork.Movie.GetAsync(id);

			if (movie == null)
			{
				return NotFound();
			}

			if (!string.IsNullOrEmpty(movie.ImageUrl))
			{
				var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, movie.ImageUrl.TrimStart('\\'));

				if (System.IO.File.Exists(oldImagePath) && !oldImagePath.Contains("default"))
				{
					System.IO.File.Delete(oldImagePath);
				}
			}

			_unitOfWork.Movie.Remove(movie);
			await _unitOfWork.SaveAsync();

			return RedirectToAction("Index");
		}
	}
}

CinemaApp.Web/Controllers/RoomController.cs
using CinemaApp.DataAccess.Repository.IRepository;
using CinemaApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace CinemaApp.Web.Controllers
{
	[Authorize(Roles = SD.Role_Employee)]
    public class RoomController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		public RoomController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public async Task<IActionResult> Index()
		{	
			var rooms = await _unitOfWork.Room.GetAllAsync();

			if (rooms == null)
			{
				return NotFound();
			}

			return View(rooms);
		}

		public async Task<IActionResult> Details(int? id)
		{	
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var room = await _unitOfWork.Room.GetByAsync(x => x.Id == id, includeProperties: "Screenings");
			
			if (room == null)
			{
				return NotFound();
			}

			foreach(var screening in room.Screenings)
			{
				screening.Movie = await _unitOfWork.Movie.GetAsync(screening.MovieId);
			}

			room.Screenings = room.Screenings.Where(x => x.StartTime.Date >= DateTime.Today).OrderBy(x => x.StartTime).ToList();

			return View(room);
		}
	}
}

CinemaApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CinemaApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinemaApp.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body class="bg-dark">
    <header>
        <nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">CinemaX</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        @if (@ViewContext.HttpContext.Request.Path == "/")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white-50" href="#movies">Movies</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Employee))
                        {
                            <li class="dropdown">
                                <a class="nav-link dropdown-toggle text-white-50" role="button" href="#" data-bs-toggle="dropdown">Content Managment</a>
                                <ul class="dropdown-menu dropdown-menu-dark border border-1 border-primary">
                                    <li><a asp-area="" asp-controller="Genre" asp-action="Index" class="dropdown-item text-white-50">Genres</a></li>
                                    <li><a asp-area="" asp-controller="Movie" asp-action="Index" class="dropdown-item text-white-50">Movies</a></li>
                                    <li><a asp-area="" asp-controller="Room" asp-action="Index" class="dropdown-item text-white-50">Screenings</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="Edit" class="dropdown-item text-white-50">Home Page</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-primary">
        <div class="container ">
            &copy; 2023 - Cinemax - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>