CinemaApp.Web/Controllers/MovieController.cs
using CinemaApp.DataAccess.Repository.IRepository;
using CinemaApp.Models.DomainModels;
using CinemaApp.Models.ViewModels;
using CinemaApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CinemaApp.Web.Controllers
{
	public class MovieController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _webHostEnvironment;

		public MovieController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
            _unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Index()
		{
			var movieGenres = await _unitOfWork.MovieGenre.GetAllAsync(includeProperties: "Movie,Genre");
			var movies = movieGenres.Select(x => x.Movie).Distinct().ToList();

			return View(movies);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Create()
		{
			var genres = await _unitOfWork.Genre.GetAllAsync();
			MovieVM movieVM = new MovieVM
			{
				Genres = genres,
				Movie = new Movie()
			};
			movieVM.Movie.ReleaseDate = DateTime.Now;
			return View(movieVM);
		}

		[Authorize(Roles = SD.Role_Employee)]
		[HttpPost]
		public async Task<IActionResult> Create(MovieVM movieVM, IFormFile? formFile)
		{
			if (ModelState.IsValid)
			{
				if (movieVM.SelectedGenreIds.Count <= 0)
				{
					ModelState.AddModelError("Movie.MovieGenres", "Movie must belongs to at least one genre.");
					movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
					return View(movieVM);
				}

				string wwwRootPath = _webHostEnvironment.WebRootPath;
				if (formFile != null)
				{
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
					string moviePath = Path.Combine(wwwRootPath, @"images\movie\");

					using (var fileStream = new FileStream(Path.Combine(moviePath, fileName), FileMode.Create))
					{
						formFile.CopyTo(fileStream);
					}
					movieVM.Movie.ImageUrl = @"\images\movie\" + fileName;
				} else
				{
					movieVM.Movie.ImageUrl = @"\images\default\default-movie-poster.jpg";
				}

				movieVM.Movie.MovieGenres = movieVM.SelectedGenreIds.Select(id => new MovieGenre { GenreId = id }).ToList();

				await _unitOfWork.Movie.AddAsync(movieVM.Movie);
				await _unitOfWork.SaveAsync();

				return RedirectToAction("Index");
			}
			movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
			return View(movieVM);
		}

		public async Task<IActionResult> Details(int? id)
		{
			var movieGenres = await _unitOfWork.MovieGenre.FindAsync(x => x.MovieId == id, includeProperties: "Movie,Genre");
			var movie = movieGenres.Select(x => x.Movie).FirstOrDefault();

			return View(movie);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var movieGenres = await _unitOfWork.MovieGenre.FindAsync(x => x.MovieId == id, includeProperties: "Movie,Genre");
			var movie = movieGenres.Select(x => x.Movie).FirstOrDefault();

			if (movie == null)
			{
				return NotFound();
			}

			MovieVM movieVM = new MovieVM
			{
				Movie = movie,
				SelectedGenreIds = movie.MovieGenres.Select(x => x.GenreId).ToList(),
				Genres = await _unitOfWork.Genre.GetAllAsync()
			};

			return View(movieVM);
		}

		[Authorize(Roles = SD.Role_Employee)]
		[HttpPost]
		public async Task<IActionResult> Edit(MovieVM movieVM, IFormFile? formFile)
		{
			if (ModelState.IsValid)
			{
				if (movieVM.SelectedGenreIds.Count <= 0)
				{
					ModelState.AddModelError("Movie.MovieGenres", "Movie must belongs to at least one genre.");
					movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
					return View(movieVM);
				}

				string wwwRootPath = _webHostEnvironment.WebRootPath;
				if (formFile != null)
				{
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
					string moviePath = Path.Combine(wwwRootPath, @"images\movie\");

					if (!string.IsNullOrEmpty(movieVM.Movie.ImageUrl))
					{
						var oldImagePath = Path.Combine(wwwRootPath, movieVM.Movie.ImageUrl.TrimStart('\\'));

						if (System.IO.File.Exists(oldImagePath) && !oldImagePath.Contains("default"))
						{
							System.IO.File.Delete(oldImagePath);
						}

					}
					using (var fileStream = new FileStream(Path.Combine(moviePath, fileName), FileMode.Create))
					{
						formFile.CopyTo(fileStream);
					}
					movieVM.Movie.ImageUrl = @"\images\movie\" + fileName;
				}

				movieVM.Movie.MovieGenres = (ICollection<MovieGenre>) await _unitOfWork.MovieGenre.FindAsync(x => x.MovieId == movieVM.Movie.Id);

				foreach (var genreId in movieVM.SelectedGenreIds)
				{
					if (!movieVM.Movie.MovieGenres.Any(x => x.GenreId == genreId))
					{
						movieVM.Movie.MovieGenres.Add(new MovieGenre { GenreId = genreId });
					}
				}

				foreach (var movieGenre in movieVM.Movie.MovieGenres)
				{
					if (!movieVM.SelectedGenreIds.Contains(movieGenre.GenreId))
					{
						_unitOfWork.MovieGenre.Remove(movieGenre);
					}
				}

				_unitOfWork.Movie.Update(movieVM.Movie);
				await _unitOfWork.SaveAsync();

				return RedirectToAction("Index");
			}
			movieVM.Genres = await _unitOfWork.Genre.GetAllAsync();
			return View(movieVM);
		}

		[Authorize(Roles = SD.Role_Employee)]
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var movie = await _unitOfWork.Movie.GetAsync(id);

			if (movie == null)
			{
				return NotFound();
			}

			if (!string.IsNullOrEmpty(movie.ImageUrl))
			{
				var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, movie.ImageUrl.TrimStart('\\'));

				if (System.IO.File.Exists(oldImagePath) && !oldImagePath.Contains("default"))
				{
					System.IO.File.Delete(oldImagePath);
				}
			}

			_unitOfWork.Movie.Remove(movie);
			await _unitOfWork.SaveAsync();

			return RedirectToAction("Index");
		}
	}
}

CinemaApp.Web/Controllers/TicketController.cs
using CinemaApp.DataAccess.Repository.IRepository;
using CinemaApp.Models.DomainModels;
using CinemaApp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CinemaApp.Web.Controllers
{
	public class TicketController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

		public TicketController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public async Task<IActionResult> Index(int? movieId)
		{	
			if (movieId == null || movieId == 0)
			{
				return NotFound();
			}

			var movieScreenings = await _unitOfWork.Screening.FindAsync(x => x.Movie.Id == movieId && x.StartTime >= DateTime.Now, includeProperties: "Movie,Room");

			if (movieScreenings == null)
			{
				return NotFound();
			}

			movieScreenings = movieScreenings.OrderBy(x => x.StartTime.TimeOfDay).ToList();
			return View(movieScreenings);
		}

		public async Task<IActionResult> Create(int? screeningId)
		{
			if (screeningId == null || screeningId == 0)
			{
				return NotFound();
			}

			var screening = await _unitOfWork.Screening.GetByAsync(x => x.Id == screeningId, includeProperties: "Movie,Tickets");

			var ticketVM = new TicketVM
			{
				Ticket = new Ticket
				{
					Price = screening.Movie.TicketPrice,
					RoomId = screening.RoomId,
					ScreeningId = screening.Id,
				},
				MovieTitle = screening.Movie.Title,
				TicketsBought = screening.Tickets,
				MovieImageUrl = screening.Movie.ImageUrl
			};

			return View(ticketVM);
		}

		[HttpPost]
		public async Task<IActionResult> Create(TicketVM ticketVM)
		{
			var tickets = await _unitOfWork.Ticket.GetAllAsync();

			if(ModelState.IsValid)
			{
				if (tickets.Any(x => x.Row == ticketVM.SelectedRowNumber && x.Number == ticketVM.SelectedSeatNumber && x.ScreeningId == ticketVM.Ticket.ScreeningId))
				{
					ModelState.AddModelError(nameof(ticketVM.SelectedSeatNumber), "This seat is already reserved.");
					ticketVM.TicketsBought = (ICollection<Ticket>?) await _unitOfWork.Ticket.FindAsync(x => x.ScreeningId == ticketVM.Ticket.ScreeningId);
					return View(ticketVM);
				}

				ticketVM.Ticket.Row = ticketVM.SelectedRowNumber;
				ticketVM.Ticket.Number = ticketVM.SelectedSeatNumber;

				await _unitOfWork.Ticket.AddAsync(ticketVM.Ticket);
				await _unitOfWork.SaveAsync();

				return RedirectToAction("Index", "Home");
			}

			return RedirectToAction("Index", "Home");
		}
	}
}

CinemaApp.Web/Views/Movie/Create.cshtml
@model MovieVM

<div class="row justify-content-center">
	<div class="card col-lg-6 shadow bg-primary bg-opacity-50 mt-4 px-0">
		<div class="card-header border-0 bg-primary">
			<div class="row">
				<div class="col-12 text-center">
					<h2 class="text-white my-0 py-2">Add Movie</h2>
				</div>
			</div>
		</div>
		<div class="card-body p-4">
			<form method="post" class="row" enctype="multipart/form-data">
				<div class="mb-3">
					<label asp-for="Movie.Title" class="text-white-50 form-label"></label>
					<input asp-for="Movie.Title" class="form-control" placeholder="Movie Title">
					<span asp-validation-for="Movie.Title" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.Description" class="text-white-50 form-label"></label>
					<textarea asp-for="Movie.Description" class="form-control" style="height:200px;" placeholder="Movie Description"></textarea>
					<span asp-validation-for="Movie.Description" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.Director" class="text-white-50 form-label"></label>
					<input asp-for="Movie.Director" class="form-control" placeholder="Directors (separated by coma if more than one)">
					<span asp-validation-for="Movie.Director" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="text-white-50 form-label">Genres</label>
					<div class="row">
						@foreach (var genre in Model.Genres)
						{
							<div class="col-4 d-flex align-items-center">
								<input type="checkbox" name="SelectedGenreIds" value="@genre.Id" /><span class="text-white-50 ms-1">@genre.Name</span>
							</div>
						}
					</div>
					<span asp-validation-for="Movie.MovieGenres" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.MainActor" class="text-white-50 form-label"></label>
					<input asp-for="Movie.MainActor" class="form-control" placeholder="Main Actors (separated by coma if more than one)">
					<span asp-validation-for="Movie.MainActor" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.Duration" class="text-white-50 form-label">Duration (min)</label>
					<input asp-for="Movie.Duration" class="form-control" placeholder="Movie Duration">
					<span asp-validation-for="Movie.Duration" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.TicketPrice" class="text-white-50 form-label"></label>
					<input asp-for="Movie.TicketPrice" class="form-control" placeholder="Ticket Price">
					<span asp-validation-for="Movie.TicketPrice" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.ReleaseDate" class="text-white-50 form-label"></label>
					<input asp-for="Movie.ReleaseDate" type="date" class="form-control" placeholder="Release Date">
					<span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="text-white-50 form-label">Movie Poster</label>
					<input type="file" id="formFile" name="formFile" class="form-control">
				</div>
				<div class="row pt-2 justify-content-center justify-content-sm-start">
					<div class="col-4 col-xl-3">
						<button type="submit" class="btn btn-primary form-control">Add</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

@section Scripts
{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}



CinemaApp.Web/Views/Movie/Details.cshtml
@model Movie

<div class="card my-4 bg-primary bg-opacity-50 border-0 p-3">
    <div class="row g-5">
        <div class="col-xl-4 col-lg-12">
            <img src="@Model.ImageUrl" class="img-fluid" alt="Movie poster">
        </div>
        <div class="col-xl-8">
            <div class="card-body">
                <h1 class="card-title text-white text-opacity-75">@Model.Title</h1>
                @foreach (var genre in Model.MovieGenres)
                {
                    <span class="text-white fw-bold text-opacity-75 bg-primary p-1 rounded">@genre.Genre.Name</span>
                }
                <br />
                <span class="text-white text-opacity-50 mt-3 d-inline-block"><i class="bi bi-clock-fill"></i> @Model.Duration min</span>
                <hr class="text-white" />
                <p class="card-text text-white text-opacity-50">
                    @Model.Description
                </p>
                <p class="card-text text-white text-opacity-50 my-2"><span class="text-white text-opacity-75 fw-bold">Directior: </span>@Model.Director</p>
                <p class="card-text text-white text-opacity-50 my-2"><span class="text-white text-opacity-75 fw-bold">Stars: </span>@Model.MainActor</p>
                <p class="card-text text-white text-opacity-50 my-2"><span class="text-white text-opacity-75 fw-bold">Price: </span>@Model.TicketPrice.ToString("C")</p>
                <div class="row justify-content-center mt-5">
                     <a role="button" asp-controller="Ticket" asp-action="Index" asp-route-movieId="@Model.Id" class="btn fs-3 text-black btn-warning rounded rounded-3 w-75">Watch Movie <i class="bi bi-film ms-2"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>

CinemaApp.Web/Views/Movie/Edit.cshtml
@model MovieVM

<div class="row justify-content-center">
	<div class="card col-lg-6 shadow bg-primary bg-opacity-50 mt-4 px-0">
		<div class="card-header border-0 bg-primary">
			<div class="row">
				<div class="col-12 text-center">
					<h2 class="text-white my-0 py-2">Edit Movie</h2>
				</div>
			</div>
		</div>
		<div class="card-body p-4">
			<form method="post" class="row" enctype="multipart/form-data">
				<input asp-for="Movie.Id" hidden/>
				<input asp-for="Movie.ImageUrl" hidden />
				<div class="mb-3">
					<label asp-for="Movie.Title" class="text-white-50 form-label"></label>
					<input asp-for="Movie.Title" class="form-control" placeholder="Movie Title">
					<span asp-validation-for="Movie.Title" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.Description" class="text-white-50 form-label"></label>
					<textarea asp-for="Movie.Description" class="form-control" style="height:200px;" placeholder="Movie Description"></textarea>
					<span asp-validation-for="Movie.Description" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.Director" class="text-white-50 form-label"></label>
					<input asp-for="Movie.Director" class="form-control" placeholder="Directors (separated by coma if more than one)">
					<span asp-validation-for="Movie.Director" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="text-white-50 form-label">Genres</label>
					<div class="row">
						@foreach (var genre in Model.Genres)
						{	
							<div class="col-4 d-flex align-items-center">
								@if (Model.SelectedGenreIds.Contains(genre.Id))
								{
									<input type="checkbox" name="SelectedGenreIds" value="@genre.Id" checked /><span class="text-white-50 ms-1">@genre.Name</span>

								} else
								{
									<input type="checkbox" name="SelectedGenreIds" value="@genre.Id"/><span class="text-white-50 ms-1">@genre.Name</span>
								}
							</div>
						}
					</div>
					<span asp-validation-for="Movie.MovieGenres" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.MainActor" class="text-white-50 form-label"></label>
					<input asp-for="Movie.MainActor" class="form-control" placeholder="Main Actors (separated by coma if more than one)">
					<span asp-validation-for="Movie.MainActor" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.Duration" class="text-white-50 form-label">Duration (min)</label>
					<input asp-for="Movie.Duration" class="form-control" placeholder="Movie Duration">
					<span asp-validation-for="Movie.Duration" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.TicketPrice" class="text-white-50 form-label"></label>
					<input asp-for="Movie.TicketPrice" class="form-control" placeholder="Ticket Price">
					<span asp-validation-for="Movie.TicketPrice" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="Movie.ReleaseDate" class="text-white-50 form-label"></label>
					<input asp-for="Movie.ReleaseDate" type="date" class="form-control" placeholder="Release Date">
					<span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="text-white-50 form-label">Movie Poster</label>
					<input type="file" id="formFile" name="formFile" class="form-control">
				</div>
				<div class="row pt-2 justify-content-center justify-content-sm-start">
					<div class="col-4 col-xl-3">
						<button type="submit" class="btn btn-primary form-control">Edit</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

@section Scripts
	{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}



CinemaApp.Web/Views/Movie/Index.cshtml
@model List<Movie>

<div class="row justify-content-center">
	<div class="card shadow border-0 bg-primary bg-opacity-50 mt-4 w-100 px-0">
		<div class="card-header bg-primary py-1">
			<div class="row">
				<div class="col-12 text-center">
					<h2 class="text-white py-2 my-0">Movie list</h2>
				</div>
			</div>
		</div>
		<div class="card-body bg-dark p-4">
			<div class="row pb-3">
				<div class="col-12 text-end">
					<a asp-controller="Movie" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i> Add New Movie</a>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-dark table-bordered table-striped">
					<thead>
						<tr class="align-middle">
							<th>Title</th>
							<th class="d-none d-md-table-cell">Director</th>
							<th class="d-none d-md-table-cell">Release Year</th>
							<th class="d-none d-lg-table-cell">Genre</th>
							<th class="d-none d-md-table-cell">Ticket Price</th>
							<th></th>

						</tr>
					</thead>
					<tbody>
						@foreach (var movie in Model)
						{
							<tr class="align-middle">
								<td class="align-middle py-1">
									<a asp-controller="Movie" asp-action="Details" asp-route-id="@movie.Id" class="text-white-50 text-decoration-none">@movie.Title</a>
								</td>
								<td class="d-none d-md-table-cell">@movie.Director</td>
								<td class="d-none d-md-table-cell">@movie.ReleaseDate.Year</td>
								<td class="d-none d-lg-table-cell">
									@foreach (var movieGenre in movie.MovieGenres)
									{
										<ul class="list-unstyled">
											<li>@movieGenre.Genre.Name</li>
										</ul>
									}
								</td>
								<td class="d-none d-md-table-cell">@movie.TicketPrice.ToString("C")</td>
								<td>
									<div class="row justify-content-between">
										<a asp-controller="Movie" asp-action="Edit" asp-route-id="@movie.Id" class="text-info text-decoration-none">
											<i class="bi bi-pencil-square"></i> Edit
										</a>
										<a asp-controller="Movie" asp-action="Delete" asp-route-id="@movie.Id" class="mt-2 text-danger text-decoration-none">
											<i class="bi bi-trash3-fill"></i> Delete
										</a>
									</div>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>